---

  - name: Check if database is already created
    shell: grep {{ item.value.oracle_db_name }}:{{ oracle_home_db }} /etc/oratab |wc -l
    with_dict: oracle_databases
    tags:
    - checkifdbexists
    register: checkdbexist

#  - debug: var=checkdbexist.stdout
#    with_items: checkdbexist.results
#    when: master_node
#    tags:
#    - checkifdbexists

  - name: Create responsefile for dbca
    template: src=dbca-create-db.rsp.{{ oracle_databases[item.0].oracle_version_db }}.j2 dest={{ oracle_rsp_stage }}/{{ oracle_dbca_rsp }}  owner={{ oracle_user }} group={{ oracle_group }} mode=644 backup=no
    with_together:
       - oracle_databases
       - checkdbexist.results
    when: master_node and item.1.stdout != "1"
    tags: 
    - dbcaresponse

  - name: Create database(s)
    shell: "{{ oracle_home_db_install }}/bin/dbca -responseFile {{ oracle_rsp_stage }}/{{ oracle_dbca_rsp }} -silent"
    with_together:
       - oracle_databases
       - checkdbexist.results
    when: master_node and item.1.stdout != "1"
    tags:
      - oradbcreate
    register: oradbcreate

  - debug: var=oradbcreate.stdout_lines
    with_items: oradbcreate.results
    tags:
     - oradbcreate

#  - name: Add default services to databases
#    shell: "{{ oracle_home_db }}/bin/srvctl add service -db {{ item.value.oracle_database }} 
#    with_dict: oracle_databases
#    when: master_node and oracle_install_option_gi == 'HA_CONFIG'
#    tags:
#      - oradbcreate
#    register: oradbcreate

  - name: Check if database is registered
    shell: "{{ oracle_home_gi }}/bin/srvctl config database "
    when: oracle_install_option_gi == 'CRS_CONFIG' or oracle_install_option_gi == 'HA_CONFIG'
    tags:
      - srvctlconfig
    register: srvctlconfig
      

  - debug: var=srvctlconfig.stdout_lines
    when: oracle_install_option_gi == 'CRS_CONFIG' or oracle_install_option_gi == 'HA_CONFIG'
    tags:
     - srvctlconfig
