asm_diskgroups:
  - diskgroup: crs
    properties:
      - {redundancy: external, ausize: 4}
    attributes:
      - {name: 'compatible.rdbms', value: 11.2.0.4.0}
      - {name: 'compatible.asm', value: "{{ oracle_install_version_gi }}"}
    disk:
      - {device: /dev/sdc, asmlabel: crs01}
  - diskgroup: data
    properties:
      - {redundancy: external, ausize: 4}
    attributes:
      - {name: compatible.rdbms, value: 11.2.0.4.0}
      - {name: 'compatible.asm', value: "{{ oracle_install_version_gi }}"}
    disk:
      - {device: /dev/sdd, asmlabel: data01}
      - {device: /dev/sde, asmlabel: data02}
  - diskgroup: fra
    properties:
      - {redundancy: external, ausize: 4}
    attributes:
      - {name: compatible.rdbms, value: 11.2.0.4.0}
      - {name: 'compatible.asm', value: "{{ oracle_install_version_gi }}"}
    disk:
      - {device: /dev/sdf, asmlabel: fra01}
      - {device: /dev/sdg, asmlabel: fra02}
      - {device: /dev/sdh, asmlabel: fra03}
