oracle_pdbs:
  - pdb_name: orclpdb
    cdb: orclcdb
    home: db1
    oracle_version_db: 12.2.0.1
    state: present
    # tablespaces:
    #      - { name: users, size: 10M, bigfile: True, autoextend: false , next: 5M, maxsize: 500M, content: permanent, state: present }
    #      - { name: app1_data, size: 10M, bigfile: True, autoextend: false , next: 5M, maxsize: 500M, content: permanent, state: present }
    # init_parameters:
    #      - {name: db_create_file_dest, value: '/tmp', scope: both, state: present}
    # services:
    #        - { name: app1_service, state: absent }
    #        - { name: app1_service,  state: present }
