---


- name: Host configuration
  hosts: aws-si-asm
  connection: local
  user: ec2-user
  become: true
  roles:
    - common
    - orahost
    - orahost-storage

- name: Oracle Grid Infrastructure installation & ASM Configuration
  hosts: aws-si-asm
  connection: local
  user: ec2-user
  become: true
  roles:
    - oraswgi-install
    - oraasm-createdg

- name: Database Server Installation & Database Creation
  hosts: aws-si-asm
  connection: local
  user: ec2-user
  become: true
  roles:
    - oraswdb-install
    - oradb-manage-db

- name: Install cx_oracle
  hosts: aws-si-asm
  connection: local
  user: ec2-user
  become: true
  roles:
    - cxoracle

- name: Configure Logrotate
  hosts: aws-si-asm
  connection: local
  user: ec2-user
  become: true
  roles:
    - orahost-logrotate
