---
- name: Apply binary patches
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  serial: 1
  roles:
    - {role: oraswdb-manage-patches}

- name: Run datapatch
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  roles:
    - {role: oradb-datapatch}
