---
- name: Host configuration
  hosts: orarac-flex
  user: ansible
  become: true
  roles:
    - common
    - orahost

- name: Storage Configuration
  hosts: orarac-flex-hub
  user: ansible
  become: true
  roles:
    - orahost-storage

- name: Oracle Grid Infrastructure installation
  hosts: orarac-flex
  user: ansible
  become: true
  roles:
    - oraswgi-install

- name: ASM Configuration, Database Server Installation & Database Creation
  hosts: orarac-flex-hub
  user: ansible
  become: true
  roles:
    - oraasm-createdg
    - oraswdb-install
    - oradb-create
