---

- name: Host configuration
  hosts: orarac-dc1
  user: ansible
  become: true
  roles:
    - common
    - orahost
    - orahost-storage

- name: ssh configuration
  hosts: vbox-rac-dc1
  user: vagrant
  become: true
  serial: 1
  roles:
    - {role: orahost-ssh, when: configure_cluster and not old_ssh_config}

- name: Oracle Grid Infrastructure installation & ASM Configuration
  hosts: orarac-dc1
  user: ansible
  become: true
  roles:
    - oraswgi-install
    - oraasm-createdg

- name: Database Server Installation & Database Creation
  hosts: orarac-dc1
  user: ansible
  become: true
  roles:
    - oraswdb-install
    - oradb-create

- name: Tweaks
  hosts: orarac-dc1
  user: ansible
  become: true
  roles:
    - cxoracle
    - orahost-logrotate
