---
namespace: opitzconsulting
name: ansible-oracle
version: 2.1.1
readme: README.md
description: Ansible collection for managing Oracle Databases
authors:
  - oravirt
  - opitzconsulting
  - Rendanic
  - bartowl
license:
  - MIT
tags:
  - database
  - oracle
repository: "https://github.com/opitzconsulting/ansible-oracle"
homepage: "https://github.com/opitzconsulting/ansible-oracle"
issues: "https://github.com/opitzconsulting/ansible-oracle/issues"

