---


- name: Host configuration
  hosts: "{{ hostgroup }}"
  become: true
  roles:
    - common
    - orahost
    - orahost-storage

- name: Oracle Grid Infrastructure installation & ASM Configuration
  hosts: "{{ hostgroup }}"
  become: true
  roles:
    - oraswgi-install
    - oraasm-createdg

- name: Database Server Installation & Database Creation
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  roles:
    - oraswdb-install
    - oradb-manage-db

- name: Tweaks
  become: true
  hosts: "{{ hostgroup | default('all') }}"
  roles:
    - cxoracle
    - orahost-logrotate

# - name: Database configuration (tablespaces, parameters etc)
#   hosts: "{{ hostgroup }}"
#   become: yes
#   roles:
#       - oradb-parameters
#       - oradb-tablespace
#       - oradb-users
