---

- name: Host configuration
  hosts: vbox-si-fs
  user: vagrant
  become: true
  roles:
    - common
    - orahost

- name: Database Server Installation & Database Creation
  hosts: vbox-si-fs
  user: vagrant
  become: true
  roles:
    - oraswdb-install
    - cxoracle
    - {role: oraswdb-manage-patches, when: apply_patches_db}
    - oradb-manage-db

- name: Configure Logrotate
  hosts: vbox-si-fs
  user: vagrant
  become: true
  roles:
    - orahost-logrotate

- name: Customize database(s)
  hosts: vbox-si-fs
  user: vagrant
  become: true
  roles:
    - oradb-manage-pdb
    - oradb-manage-tablespace
    - oradb-manage-parameters
    - oradb-manage-redo
    - oradb-manage-roles
    - oradb-manage-users
    - oradb-manage-grants
    - oradb-manage-services

- name: Run Datapatch
  hosts: vbox-si-fs
  user: vagrant
  become: true
  roles:
    - {role: oradb-datapatch, when: apply_patches_db}
