---
- name: Host configuration
  hosts: vbox-rac-all
  user: vagrant
  become: true
  roles:
    - common
    - orahost
- name: ssh configuration
  hosts: vbox-rac-all
  user: vagrant
  become: true
  serial: 1
  roles:
    - {role: orahost-ssh, when: configure_cluster and not old_ssh_config}

- name: Storage Configuration
  hosts: vbox-rac-hub
  user: vagrant
  become: true
  roles:
    - orahost-storage

- name: Oracle Grid Infrastructure installation
  hosts: vbox-rac
  user: vagrant
  become: true
  roles:
    - oraswgi-install

- name: ASM Configuration, Database Server Installation & Database Creation
  hosts: vbox-rac-hub
  user: vagrant
  become: true
  roles:
    - oraasm-createdg
    - oraswdb-install
    - oradb-manage-db

- name: Install cx_oracle
  hosts: vbox-rac-hub
  user: vagrant
  become: true
  roles:
    - cxoracle

- name: Configure Logrotate
  hosts: vbox-rac-hub
  user: vagrant
  become: true
  roles:
    - orahost-logrotate
