---
# tasks file for manage-db

- name: manage-db | set fact for Listener
  set_fact:
      create_listener: "{{ create_listener }}"
  with_items: "{{ oracle_databases }}"
  loop_control:
     loop_var: dbh
  tags: set_fact

- include_tasks: listener.yml
  with_items:
      - "{{ oracle_databases }}"
  loop_control:
    loop_var: dbh
  when: create_listener and oracle_databases is defined
  tags: listener

- name: manage-db | Add change-pdb script
  template:
         src: pdb.sql.j2
         dest: "{{oracle_user_home}}/.Scripts/chpdb.sql"
         owner: "{{ oracle_user }}"
         group: "{{ oracle_group }}"
  tags: sql_script

- include_tasks: manage-db.yml
  with_items:
      - "{{ oracle_databases }}"
  loop_control:
    loop_var: dbh
  when: oracle_databases is defined
  tags: create_db,dbca,customdbcatemplate,dotprofile_db


- name: manage-db | Check if database is running
  shell: ps -ef |grep pmon |grep -v grep
  tags:
   - psout
  register: psout
  changed_when: False
  failed_when: False
  ignore_errors: True


- debug: var=psout.stdout_lines
  changed_when: False
  failed_when: False
  when: psout is defined
  tags:
   - psout
