---
galaxy_info:
  role_name: oraasm-createdg
  author: Mikael Sandström (oravirt@gmail.com, http://oravirt.wordpress.com)
  description: Creates ASM Diskgroups

  license: MIT

  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8

  galaxy_tags:
    - database
    - oracle

dependencies: []
