oracle_home_db: "{%- if item is defined -%}
                    {%- if db_homes_config[item.home]['oracle_home'] is defined  -%}
                         {{db_homes_config[item.home]['oracle_home']}}
                    {%- else -%}
                         {{oracle_base}}/{{db_homes_config[item.home]['version']}}/{{db_homes_config[item.home]['home']}}
                    {%- endif -%}
                 {%- elif dbh is defined -%}
                    {%- if db_homes_config[dbh.home]['oracle_home'] is defined  -%}
                         {{db_homes_config[dbh.home]['oracle_home']}}
                    {%- else -%}
                         {{oracle_base}}/{{db_homes_config[dbh.home]['version']}}/{{db_homes_config[dbh.home]['home']}}
                    {%- endif -%}
                 {%- endif -%}"

db_version: "{%- if item is defined and db_homes_config[item.home] is defined -%}
                    {%- if db_homes_config[item.home]['version'] is defined  -%}
                         {{db_homes_config[item.home]['version']}}
                    {%- endif -%}
                {%- elif dbh is defined and db_homes_config[dbh.home] is defined -%}
                    {%- if db_homes_config[dbh.home]['version'] is defined  -%}
                         {{db_homes_config[dbh.home]['version']}}
                    {%- endif -%}
                {%- elif item[1] is defined and db_homes_config[item[1].home] is defined -%}
                    {%- if db_homes_config[item[1].home]['version'] is defined  -%}
                         {{db_homes_config[item[1].home]['version']}}
                    {%- endif -%}
                {%- endif -%}"

db_homes_config:
  12201-base:
    home: db1
    version: 12.2.0.1
    edition: EE



db_homes_installed:
     - home: 12201-base
       state: present
