---

  - name: ASMCA | Create script to build asm-diskgroups
    template: src=asmca-createdg.sh.j2 dest="{{ oracle_rsp_stage }}/asmca-createdg-{{ item }}.sh"  owner="{{ grid_user }}" group={{ oracle_group }} mode=744 backup=yes
    with_items: asm_diskgroups
    when: master_node and item != oracle_asm_crs_diskgroup
    tags: asmca

  - name: ASMCA | Create ASM diskgroups
    shell: "{{ oracle_rsp_stage }}/asmca-createdg-{{ item }}.sh"
    with_items: asm_diskgroups
    sudo: yes
    sudo_user: "{{ grid_user }}"
    when: master_node and item != oracle_asm_crs_diskgroup
    ignore_errors: True
    tags: asmca
    register: asmca

  - debug: var=asmca.stdout_lines
    with_items: asmca.results
    tags: asmca

  - name: ASMCA | List ASM diskgroups
    shell: "{{ oracle_home_gi }}/bin/srvctl status diskgroup -g {{ item }}"
    with_items: asm_diskgroups
    sudo: yes
    sudo_user: "{{ grid_user }}"
    when: master_node and oracle_install_version_gi == "11.2.0.4"
    tags: srvctlasm
    register: srvctlasm

  - name: ASMCA | List ASM diskgroups
    shell: "{{ oracle_home_gi }}/bin/srvctl status diskgroup -diskgroup {{ item }}"
    with_items: asm_diskgroups
    sudo: yes
    sudo_user: "{{ grid_user }}"
    when: master_node and oracle_install_version_gi != "11.2.0.4"
    tags: srvctlasm
    register: srvctlasm


  - debug: var=srvctlasm.stdout_lines
    with_items: srvctlasm.results
    tags: srvctlasm
