---
name: Ansible Lint

on:
  pull_request:
    branches:
      - oc
      - master
  push:
    branches:
      - 'pr*'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v2

      - name: Lint roles
        # Use custom action repo due to open PRs 43 and 48
        uses: ansible-community/ansible-lint-action@v6.5.2
        with:
          targets: |
            roles/*
            
          args: ""
